### ISSUE TITLE
New Session not possible

### ISSUE THREAD

**Issue by DasJott** [halturin/gsql#1]
If I want to create a new session, I constantly get the following error message:
![image](https://user-images.githubusercontent.com/6298761/44142428-6bb6537a-a080-11e8-839f-12bb436ab4ae.png)

The mysql DB runs in a docker container and is available on localhost:3306 which I of course set up correctly in the according dialog.
I would like to use this because workbench crashes.

(The german text says: "File or directory not found")

**Comment by halturin** [comment]
Hi,
try to specify IP address, instead of 'localhost'

**Comment by DasJott** [comment]
Oh yes. That worked pretty fine!

Didn't think of that... thank you!
